[[org]]
id = "lnpbp"
name = "LNP/BP Standards Association"
domain = "lnp-bp.org"
certificate = "cert1....."

[[signer]]
id = "dr-orlovsky"
org = "lnpbp"
name = "Dr Maxim Orlovsky"
email = "orlovsky@lnp-bp.org"
certificate = "cert1....."

[[schema]]
api = "rgb20"
name = "RGB20 Legacy Base Schema"
org = "LNP/BP Standards Association"
domain = "lnp-bp.org"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>", "LNP/BP Community"]
license = "CC-0"
schema = "z1....."
format = "yaml"
signatures = { dr-orlovsky = "sig1...", lnpbp = "sig1..." }

[[schema]]
api = "rgb20"
name = "RGB20 Legacy Complete Schema"
org = "LNP/BP Standards Association"
domain = "lnp-bp.org"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>", "LNP/BP Community"]
license = "CC-0"
schema = "z1....."
format = "yaml"
signatures = { dr-orlovsky = "sig1...", lnpbp = "sig1..." }
